name: Автоматический CI/CD

on:
  push:
    branches:
      - main  # Запускать только при пуше в main
  pull_request:
    branches:
      - main  # Запускать при создании PR в main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Запуск тестового скрипта
        run: |
          chmod +x script.sh
          ./script.sh
